[package]
name = "day04"
version = "0.1.0"
authors = ["Paul-Maxime <github@paulmaxime.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
